// Thin TypeScript wrapper around the Mathesis wasm engine.
//
// `src/pkg/` is generated by `wasm-pack build --target web` (in CI, or via
// `npm run wasm` locally) and is intentionally git-ignored — it is a build
// artifact, not source.
import init, { evaluate, version } from './pkg/mathesis.js'

export interface EvalResult {
  ok: boolean
  /** Plain-text form of the result (present when ok). */
  text?: string
  /** TeX form for KaTeX (present when ok). */
  tex?: string
  /** Human-readable message (present when not ok). */
  error?: string
}

let ready: Promise<unknown> | null = null

/** Load and instantiate the wasm module exactly once. */
function ensureReady(): Promise<unknown> {
  if (!ready) ready = init()
  return ready
}

/** Evaluate one line of Mathesis input. */
export async function evaluateInput(src: string): Promise<EvalResult> {
  await ensureReady()
  return JSON.parse(evaluate(src)) as EvalResult
}

/** The engine's crate version. */
export async function engineVersion(): Promise<string> {
  await ensureReady()
  return version()
}
